
package colegio;

import java.util.HashSet;

/**
 *
 * @author Gabriel Jara
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private HashSet<Alumno> listaAlumnos;
    private HashSet<Materia> listaMaterias;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desktop_principal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_cargarAlumno = new javax.swing.JMenuItem();
        menu_verMaterias = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_cargarMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_inscripcionMaterias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú principal del Colegio");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(575, 588));

        desktop_principal.setPreferredSize(new java.awt.Dimension(421, 323));

        javax.swing.GroupLayout desktop_principalLayout = new javax.swing.GroupLayout(desktop_principal);
        desktop_principal.setLayout(desktop_principalLayout);
        desktop_principalLayout.setHorizontalGroup(
            desktop_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        desktop_principalLayout.setVerticalGroup(
            desktop_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jLabel1.setText("COLEGIO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(desktop_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(93, 93, 93)
                .addComponent(desktop_principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jMenu1.setText("Alumnos");

        menu_cargarAlumno.setText("Cargar Alumnos");
        menu_cargarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cargarAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cargarAlumno);

        menu_verMaterias.setText("Materias asignadas");
        menu_verMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_verMateriasActionPerformed(evt);
            }
        });
        jMenu1.add(menu_verMaterias);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");

        menu_cargarMaterias.setText("Agregar materias");
        menu_cargarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cargarMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(menu_cargarMaterias);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Inscripción");

        menu_inscripcionMaterias.setText("Inscribir en materias");
        menu_inscripcionMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_inscripcionMateriasActionPerformed(evt);
            }
        });
        jMenu3.add(menu_inscripcionMaterias);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_cargarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cargarAlumnoActionPerformed
        desktop_principal.removeAll();
        desktop_principal.repaint();
        InternalAlumnos formCargaAlumnos = new InternalAlumnos();
        desktop_principal.add(formCargaAlumnos);
        formCargaAlumnos.setVisible(true);
    }//GEN-LAST:event_menu_cargarAlumnoActionPerformed

    private void menu_cargarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cargarMateriasActionPerformed
        desktop_principal.removeAll();
        desktop_principal.repaint();
        InternalMateria formCargaMateria = new InternalMateria();
        desktop_principal.add(formCargaMateria);
        formCargaMateria.setVisible(true);
        formCargaMateria.setListaMaterias(listaMaterias);
    }//GEN-LAST:event_menu_cargarMateriasActionPerformed

    private void menu_inscripcionMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inscripcionMateriasActionPerformed
       desktop_principal.removeAll();
        desktop_principal.repaint();
        InternalInscripcion formInscripcion = new InternalInscripcion();
        desktop_principal.add(formInscripcion);
        formInscripcion.setVisible(true);
    }//GEN-LAST:event_menu_inscripcionMateriasActionPerformed

    private void menu_verMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_verMateriasActionPerformed
       desktop_principal.removeAll();
        desktop_principal.repaint();
        InternalMostrarMaterias formMostrarMaterias = new InternalMostrarMaterias();
        desktop_principal.add(formMostrarMaterias);
        formMostrarMaterias.setVisible(true);
    }//GEN-LAST:event_menu_verMateriasActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    public void cargarListaAlumnos(HashSet<Alumno> lista){
        this.listaAlumnos = lista;
    }
    
    public void cargarListaMaterias(HashSet<Materia> lista){
        this.listaMaterias = lista;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop_principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menu_cargarAlumno;
    private javax.swing.JMenuItem menu_cargarMaterias;
    private javax.swing.JMenuItem menu_inscripcionMaterias;
    private javax.swing.JMenuItem menu_verMaterias;
    // End of variables declaration//GEN-END:variables
}
